

@baseUrl = https://bizradarapi.xingsuancn.com


### 获取商机列表
GET {{baseUrl}}/api/v1/contents/bili/notes


### API文档
https://api.itapi.cn/user/doc?id=85


# tX1YqbmsYJEtZJe7NSzCmhVuvZ

### 小红书热搜
GET https://api.itapi.cn/api/hotnews/xiaohongshu?key=tX1YqbmsYJEtZJe7NSzCmhVuvZ


### 抖音热搜
GET https://api.itapi.cn/api/hotnews/douyin?key=tX1YqbmsYJEtZJe7NSzCmhVuvZ

### B站热搜
GET https://api.itapi.cn/api/hotnews/bilibili?key=tX1YqbmsYJEtZJe7NSzCmhVuvZ



